language: python
dist: bionic
python:
  - "3.8"
os: linux

install:
  - pip install -r requirements.txt

#before_script:
#  - python3.8 manage.py migrate

script:
  - python setup_environment.py
  - python manage.py test