# Generated by Django 3.0.5 on 2020-04-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='icons')),
                ('published', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='api.Category')),
                ('next_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Article.next_article+', to='api.Article')),
                ('previous_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Article.previous_article+', to='api.Article')),
            ],
        ),
    ]
