# Generated by Django 3.0.5 on 2020-04-21 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='article',
            name='next_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Article.next_article+', to='api.Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='previous_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Article.previous_article+', to='api.Article'),
        ),
    ]
