# Generated by Django 3.0.5 on 2020-04-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200422_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_test',
            field=models.TextField(default='default', max_length=500),
            preserve_default=False,
        ),
    ]
