# Generated by Django 3.0.5 on 2020-04-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_preview_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='preview_test',
            new_name='preview_text',
        ),
    ]
