# Generated by Django 3.0.5 on 2020-04-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200430_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='api.Category'),
        ),
    ]
