# Generated by Django 3.0.5 on 2020-05-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_article_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
    ]
