# Generated by Django 3.0.5 on 2020-05-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_article_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
